### ISSUE TITLE
Opening link, reittiloki does not obey zoom level and position

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#524]
Looks like when opening link ui defaults to zoom level and position to show whole route. It is intended to obey the url so exact position is show. 

Example here is link for close zoom of first stop of route https://reittiloki.hsl.fi/journey/20200117/124800/2203/2/0018_487?date=2020-01-17&route.routeId=2203&route.direction=2&route.originStopId=2116290&live=false&tab=&time=12%3A48%3A00&mapZoom=14&details-tab=journey-events&mapView=60.232312033385874%2C24.822406768798828&vehicle=0018%2F487

**Comment by danieldunderfelt** [comment]
It seems to work for me, but I know what you mean and we can fix it so that it works more consistently.

**Comment by danieldunderfelt** [comment]
I can sometimes reproduce this, and sometimes not. The issue is that the map state (zoom and location) is usually included in the url, so if a url with a route is shared that also includes the map state, it's quite impossible to know which one the user wanted to focus on. After all, we want Reittiloki to center on both.

Essentially we have to decide which one the application should center on if the URL includes both.

**Comment by danieldunderfelt** [comment]
I'm going to assume that we always want to center and zoom according to the URL when landing in the app through a shared URL, and only center on routes and stops when they are selected manually in the app. Is this OK @samijuhani ?

**Comment by samijuhani** [comment]
Yes. The first use case for shared url was to "let other user see exactly what I am seeing" when sending link. Including position, zoom level, etc. Other cases as coming from route search or OMM link (only journey data) can and need to zoom to whole route level.

**Comment by danieldunderfelt** [comment]
Yes, these cases were conflicting. I'm refactoring the rather messy centering logic now to prioritize the map state in the URL and after that center on stops or routes as they are selected. Indeed, when coming from OMM, there si no map state in the URL.

**Comment by danieldunderfelt** [comment]
This is now fixed in dev and stage!

**Comment by samijuhani** [comment]
Should this be in prod? First link in issue still centers to whole route but taking a new link works fine.

**Comment by danieldunderfelt** [comment]
Prod probably doesn't have the latest version of this feature. It will soon though!

**Comment by samijuhani** [comment]
Seems fine in stage
